# -*- coding: utf-8 -*-
"""Chatbot in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bs_7NJ7ZBn84oBKux-tzWSzfqyDaNT21
"""

pip install chatterbot

pip install chatterbot_corpus

from chatterbot import ChatBot

bot = ChatBot(
    'RSCOE',  
    logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.TimeLogicAdapter'],
)

from chatterbot.trainers import ChatterBotCorpusTrainer

trainer = ChatterBotCorpusTrainer(bot)

trainer.train('/content/sample_data/Chatterbot_Corpus_English')



name=input("Enter Your Name: ")
print("Hi "+name+", how can I help you?")
while True:
    request=input(name+':')
    if request=='Bye' or request =='bye':
        print('RSCOE: Bye')
        break
    else:
        response=bot.get_response(request)
        # get_reponses() is a method of chatbot instance
        print('RSCOE:',response)